name: Verify

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Format
        run: pnpm format
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Lint repo
        run: pnpm lint:repo
      - name: Lint
        run: pnpm lint
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: lint'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build
        run: pnpm build

  types:
    name: Types
    needs: [lint, format]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Check types
        run: pnpm typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Test
        run: pnpm test:ci
